import { z } from "zod";
import { processTurnInputSchema, extractionResultSchema } from "../../../memory-agent/src/contracts";
import { memoryCommandSchema } from "./management-schema";
const timestamp = z.string().datetime();
const dialogueCommand=z.object({story_id:z.string(),operation_id:z.string(),base_revision:z.number().int().positive(),input:z.string().min(1).max(12000),dialogue_action:z.enum(["reply","finish"]),dialogue_id:z.string(),dialogue_revision:z.number().int().positive(),retry_failed:z.boolean().optional()}).strict();
const conversation=z.object({id:z.string(),run_id:z.string(),revision:z.number().int().positive(),status:z.enum(["active","ready","closed","abandoned"]),speaker:z.object({speaker_id:z.string().nullable(),speaker_name:z.string(),utterance:z.string()}),player:z.object({id:z.string().nullable(),name:z.string()}),messages:z.array(z.object({role:z.enum(["npc","user"]),name:z.string(),text:z.string(),operation_id:z.string()}).strict()).min(1),exchanges:z.array(z.object({command:dialogueCommand,fingerprint:z.string(),status:z.enum(["running","failed","done"]),attempt:z.number().int().positive(),model_id:z.string(),error:z.string().optional(),result:z.object({utterance:z.string(),finished:z.boolean()}).optional()}).strict()),continuation_id:z.string(),continuation_revision:z.number().int().positive().optional()}).strict();
const base = z.object({ conversations:z.array(conversation).optional(), version: z.literal(1), revision: z.number().int().positive(), snapshot: z.object({}).passthrough(), summary: z.object({ summary: z.string(), unresolved_threads: z.array(z.string()) }), current_time: z.string(), current_location: z.string(),
  turns: z.array(z.object({ reply_to: z.string().optional(), id: z.string(), chapter: z.number().int().positive(), input: z.string(), prose: z.object({}).passthrough(), memory: z.object({}).passthrough(), created_at: timestamp }).strict()),
  chapters: z.array(z.object({ id: z.string(), number: z.number().int().positive(), source_turn_ids: z.array(z.string()), content: z.string(), summary: z.object({ summary: z.string(), unresolved_threads: z.array(z.string()) }) }).strict()),
  runs: z.array(z.object({ pipeline: z.enum(["direct_v1", "interactive_v1", "dialogue_v2"]).optional(), reply_to: z.string().optional(), operation_id: z.string(), fingerprint: z.string(), base_revision: z.number().int().positive(), input: z.string().min(1).max(12000), close_chapter: z.boolean(), status: z.enum(["running", "blocked", "waiting_dialogue", "succeeded", "abandoned"]), steps: z.record(z.string(), z.unknown()), error: z.string().optional(), created_at: timestamp }).strict()),
  memory_journal: z.array(z.object({ input: processTurnInputSchema, extraction: extractionResultSchema, created_at: timestamp }).strict()),
  seed_snapshot: z.object({}).passthrough().optional(),
  audit: z.array(z.object({ operation_id: z.string(), action: z.string(), fingerprint: z.string(), created_at: timestamp, detail: z.unknown() }).strict()).optional(),
  memory_actions: z.array(z.object({ after_turn: z.number().int().nonnegative(), operation_id: z.string(), created_at: timestamp, command: memoryCommandSchema }).strict()).optional(),
}).strict();
export function validateBackupShape(session: unknown) { return base.parse(session); }
