import type { StoryWorld } from "@/generated/story-world";
import type { CharacterProfiles } from "@/generated/character-profiles";
export type { StoryWorld, CharacterProfiles };
export type Character = CharacterProfiles["characters"][number];
export type Relationship = CharacterProfiles["relationships"][number];
export type TimelineEvent = StoryWorld["timeline"][number];
export type PresetId = "western_fantasy" | "eastern_wuxia";
export type FactStatus = "draft" | "pending_confirmation" | "confirmed" | "rejected";
export type FactSource = "user_explicit" | "user_edited" | "ai_inferred" | "ai_suggestion";
export type Fact<T = string> = { value: T; source: FactSource; status: FactStatus; locked: boolean; evidence: string[]; updated_at: string };
export type DocumentKind = "world" | "characters";
export type RevisionTarget = "world" | "timeline" | "npc";
export type ValidationIssue = { code: string; path: string; message: string };
export type AppError = { code: string; userMessage: string; retryable: boolean; requestId?: string; fieldErrors?: ValidationIssue[] };
export type CharacterClue = { label: string; identity: string; evidence: string[]; existing_character_id: string | null; controlled_by: "npc" | "user"; ambiguity: string | null };
export type RecognitionResult = { summary: string; character_clues: CharacterClue[]; hard_constraints: string[]; ambiguities: string[]; questions: { question: string; blocking: boolean }[] };
export type StoryMessage = { id: string; role: "user" | "assistant" | "system"; content: string; created_at: string };
export type AppliedOperation = { operation_id: string; fingerprint: string; revision: number };
export type StorySnapshot = { snapshot_version: 1; preset_id: PresetId; snapshot_revision: number; world: StoryWorld; characters: CharacterProfiles; messages: StoryMessage[]; input: string; recognition: RecognitionResult | null; timeline_suggestions: TimelineEvent[]; operations: AppliedOperation[]; updated_at: string };
export type StoryContext = { story_idea: string; user_notes: string[] };
export type FieldTarget = { document: DocumentKind; path: string };
export type AgentEndpoint = "framework" | "npcs" | "revise" | "field";
export type AgentRequest = { operation_id: string; base_revision: number; preset_id: PresetId; input: string; world: StoryWorld; characters: CharacterProfiles; recognition: RecognitionResult | null; target?: RevisionTarget; character_id?: string; context?: StoryContext; field?: FieldTarget };
export type FrameworkResult = { world: StoryWorld; recognition: RecognitionResult; assistant_message: string };
export type NpcResult = { characters: CharacterProfiles; timeline_suggestions: TimelineEvent[]; warnings: string[]; assistant_message: string };
export type RevisionResult = { world?: StoryWorld; characters?: CharacterProfiles; timeline_suggestions?: TimelineEvent[]; warnings: string[]; assistant_message: string };
export type Candidate = { operation_id: string; base_revision: number; fingerprint: string; world: StoryWorld; characters: CharacterProfiles; timeline_suggestions: TimelineEvent[]; recognition: RecognitionResult | null; summary: string; warnings: string[]; origin?: AgentEndpoint; field?: FieldTarget; base?: { world: StoryWorld; characters: CharacterProfiles; story_idea: string; preset_id: PresetId; timeline_suggestions: TimelineEvent[] } };
export type ProviderStatus = { configured: boolean; model: string | null; used: number; limit: number; remaining: number; configuration_error?: string };
export type WorkbenchModel = { snapshot: StorySnapshot; busy: boolean; stage: string; error: AppError | null; savedAt: string | null; candidate: Candidate | null; issues: ValidationIssue[]; candidateCanApply: boolean; autoNpcs: boolean; provider: ProviderStatus | null; canUndo: boolean; restored: boolean; canStartNewAttempt: boolean };
export type WorkbenchActions = {
  setPreset: (preset: PresetId) => void; setInput: (text: string) => void;
  generateFramework: () => Promise<void>; generateNpcs: () => Promise<void>;
  revise: (target: RevisionTarget, instruction: string, characterId?: string) => Promise<void>;
  suggestField: (document: DocumentKind, path: string, instruction: string) => Promise<void>;
  setAutoNpcs: (enabled: boolean) => void;
  editFact: (document: DocumentKind, path: string, value: string | string[]) => void;
  setFactStatus: (document: DocumentKind, path: string, status: FactStatus) => void;
  toggleLock: (document: DocumentKind, path: string) => void;
  confirmAll: () => void; addCharacter: () => void; removeCharacter: (id: string) => void;
  mergeCharacters: (sourceId: string, targetId: string) => void;
  addTimelineEvent: () => void; removeTimelineEvent: (id: string) => void;
  editTimelineMeta: (id: string, values: Partial<Pick<TimelineEvent, "order" | "period" | "related_character_ids" | "related_location_ids" | "after_event_ids">>) => void;
  acceptCandidate: () => void; rejectCandidate: () => void; acceptTimelineSuggestion: (id: string) => void; rejectTimelineSuggestion: (id: string) => void;
  undo: () => void; save: () => void; exportJson: (document: DocumentKind) => void; restart: () => void; clearData: () => void; dismissError: () => void;
  answerQuestion: (question: string, answer: string) => void;
  startNewAttempt: () => Promise<void>;
};
export type WorkbenchProps = { model: WorkbenchModel; actions: WorkbenchActions };
